version: "3.9"
services:
  order-quantity-analyzer:
    build:
      context: .
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/orderanalyzer
      SPRING_DATASOURCE_USERNAME: orderanalyzer
      SPRING_DATASOURCE_PASSWORD: orderanalyzer
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    ports:
      - "8080:8080"
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
  db:
    image: "postgres:15.6"
    container_name: db
    environment:
      POSTGRES_DB: orderanalyzer
      POSTGRES_USER: orderanalyzer
      POSTGRES_PASSWORD: orderanalyzer
      TZ: "UTC"
      PGTZ: "UTC"
    expose:
      - "5432"
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 15
  redis:
    image: "redis:6.2.14"
    container_name: redis
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
    ports:
      - "6379:6379"

