spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/orderanalyzer"
    username: "orderanalyzer"
    password: "orderanalyzer"
  data:
    redis:
      host: "localhost"
      port: 6379