package com.cleanhub.orderquantityanalyzer.testutil;

import com.cleanhub.orderquantityanalyzer.infrastructure.webclient.customerLogo.CustomerLogo;

import java.util.List;
import java.util.UUID;
import java.util.stream.Collectors;
import java.util.stream.IntStream;

public class TestCustomerLogoFactory {

    /**
     * @return List of 10 random customerLogos generated by {@link #getCustomerLogo()}
     */
    public static List<CustomerLogo> getCustomerLogos() {
        return getCustomerLogos(10);
    }

    /**
     * @param count of customerLogos to be returned
     * @return List of random customerLogos using {@code count}, generated by {@link #getCustomerLogo()}
     */
    public static List<CustomerLogo> getCustomerLogos(int count) {
        return IntStream.range(0, count)
                .mapToObj(i -> getCustomerLogo())
                .toList();
    }

    /**
     * @return A customerLogo using random UUIDs for strings delegating to {@link #getCustomerLogo(String, String)}
     */
    public static CustomerLogo getCustomerLogo() {
        return getCustomerLogo(UUID.randomUUID().toString(), UUID.randomUUID().toString());
    }

    /**
     * @return A customerLogo from passed parameters
     */
    public static CustomerLogo getCustomerLogo(String companyName, String landingPageRoute) {
        return new CustomerLogo(companyName, landingPageRoute);
    }

}
